### PR TITLE
Refactor/fix AuthCallbackRequest.initSessionUserAuth()

### LINKED ISSUE #27: Fix AuthCallbackRequest.initSessionUserAuth
`AuthCallbackRequest.initSessionUserAuth` is still using an old param signature (expecting an Express `session`, but it's now getting an RP `Session` object.

Causing downstream bug https://github.com/solid/node-solid-server/issues/720

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Refactor/fix to take into account changes to the RP Session object. Also, set up `session.credential` property as described in the [request flow doc](https://github.com/solid/solid-architecture/blob/master/server/request-flow.md).

Fixes #27 and downstream https://github.com/solid/node-solid-server/issues/720

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
cc @kjetilk / @RubenVerborgh for review.

File: src/handlers/auth-callback-request.js [hunk 1]
```diff
@@ -110,25 +111,26 @@ class AuthCallbackRequest {
...
+    try {
+      const webId = await this.oidcManager.webIdFromClaims(rpSession.idClaims)
+      this.session.userId = webId
+      this.session.credentials = {
+        webId,
+        idClaims: rpSession.idClaims,
+        authorization: rpSession.authorization
+      }
+    } catch (err) {
+      let error = new Error('Could not verify Web ID from token claims')
```
Comment (RubenVerborgh) [inline src/handlers/auth-callback-request.js]: Why no HttpError as in the other lib?

Comment (dmitrizagidulin) [reply src/handlers/auth-callback-request.js]: Just haven't introduced it into this repo yet.
